@WeatherAPI_HostAddress = http://localhost:5185

GET {{WeatherAPI_HostAddress}}/temperature
Accept: application/json

###

GET {{WeatherAPI_HostAddress}}/wind-direction
Accept: application/json

###

GET {{WeatherAPI_HostAddress}}/weather/Warszawa
Accept: application/json

###
